version: '2'
services:
    mmsnap_web-app:
        image: mmsnap_web
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mmsnap_web-mysql:3306/mmsnap_web?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mmsnap_web-mysql:
        extends:
            file: mysql.yml
            service: mmsnap_web-mysql
